theme: jekyll-theme-minimal
title: Remy Marquis
description: A Machine Learning, Android development and Chinese language enthusiast
logo: /assets/img/logo.jpg
show_downloads: false
google_analytics: UA-10359235-13