#theme: jekyll-theme-minimalistic
remote_theme: "rmarquis/jekyll-theme-minimalistic"
title: Remy Marquis
logo: /assets/img/logo.jpg
description: A Machine Learning, Data Science and Chinese language enthusiast.
favicon: true
color-scheme: auto

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/rmarquis
  - name: Certifications
    icon: <i class="fa-solid fa-award"></i>
    link: ./certifications

navigation:
  - name: Home
    link: ./
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Computer Sciences
    link: ./cs.html
  - name: Machine Learning
    link: ./ml.html
