#theme: jekyll-theme-minimal
remote_theme: "rmarquis/minimal"
title: Remy Marquis
description: A Machine Learning, Data Science and Chinese language enthusiast.
logo: /assets/img/logo.jpg
show_downloads: false
google_analytics: UA-10359235-13
theme_settings:
  # Icons
  rss: false
  email_address: "remy.marquis@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "rmarquis"
  gitee:
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube: