#theme: jekyll-theme-minimalist
remote_theme: "rmarquis/minimalist"
title: Rémy Marquis
logo: /assets/img/logo.jpg
email: remy.marquis@gmail.com
blank_title: true
favicon: true
description: A Machine Learning and Chinese language enthusiast.
show_downloads: false
google_analytics: G-G1XM6DEM68
color-scheme: auto

sidebar:
- name: GitHub
  icon: fa-brands fa-github
  link: https://github.com/rmarquis
- name: Certificates
  icon: fa-solid fa-award
  link: ./ct
