#theme: jekyll-theme-minimalistic
remote_theme: "rmarquis/jekyll-theme-minimalistic"
title: Remy Marquis
logo: /assets/img/logo.jpg
email: remy.marquis@gmail.com
description: A Machine Learning, Data Science and Chinese language enthusiast.
favicon: true
color-scheme: auto

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/rmarquis
  - name: Certifications
    icon: <i class="fa-solid fa-award"></i>
    link: ./ct

navigation:
  - name: Home
    link: ./
  - name: Computer Sciences
    link: ./cs
  - name: Machine Learning
    link: ./ml
